round:
    time: 2
    team1: 'c'
    team2: '9'
errors:
    parametersError: 'Niepoprawna ilosc argumentow!'
    permissionError: 'Nie masz permisji!'
messages:
    deathMessage: '{1}&r zabil {2}'
    joinHelp: '&lAby dolaczyc wpisz /start'
    winMessage: '&lWygrala druzyna {1}'
    noWinMessage: '&lRemis'
    hasTeam: 'Juz jestes w grze'
commands:
    join: 'start'