round:
    time: 5
    spawn: '-71 77 441'
    team1:
        name: 'RED'
        color: 'c'
        spawn: '-71 77 462'
    team2:
        name: 'BLUE'
        color: '9'
        spawn: '-71 77 441'
errors:
    parameters: 'Niepoprawna ilosc argumentow!'
    permission: 'Nie masz permisji!'
messages:
    death: '{0}&r zabil {1}'
    joinHelp: '&lAby dolaczyc wpisz /{0}'
    startHelp: '&lAby spawdzic statystyki wpisz /{0}'
    startHelp1: '&lAby zobaczyc, ile zostalo czasu wpisz /{0}'
    win: '&lWygrala druzyna {0}'
    noWin: '&lRemis'
    hasTeam: '&cJuz jestes w grze'
    time: '&bPozostalo {0} do konca rundy'
commands:
    join: 'start'
    time: 'czas'
    stats: 'staty'