round:
    time: 5
    team1: 'c'
    team2: '9'
errors:
    parametersError: 'Niepoprawna ilosc argumentow!'
    permissionError: 'Nie masz permisji!'
messages:
    deathMessage: '{0}&r zabil {1}'
    joinHelp: '&lAby dolaczyc wpisz /start'
    winMessage: '&lWygrala druzyna {0}'
    noWinMessage: '&lRemis'
    hasTeam: '&cJuz jestes w grze'
    time: '&bPozostalo {0} do konca rundy'
commands:
    join: 'start'
    time: 'czas'
    stats: 'staty'